// Start of autogenerated code
use strum_macros::EnumString;
use std::fmt;
const TM_DEF: &str = "1RB2LA1LA_2LA0RA2RC_---0LC2RA";
#[derive(Debug, Clone)]
pub enum SimError {
    Halted,
    UndefinedTransition,
}
impl fmt::Display for SimError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Self::Halted => write!(f, "Halted"),
            Self::UndefinedTransition => write!(f, "Undefined transition"),
        }
    }
}
#[derive(PartialEq, Eq)]
pub enum HigherState {
    Left,
    Right,
    RightSlow,
}
#[derive(Debug, Default, PartialEq, EnumString, Copy, Clone, Eq, Hash)]
pub enum RunSymbolType {
    #[default]
    X,
    Q,
    C,
    F,
}
#[derive(Debug, PartialEq, EnumString, Copy, Clone, Eq, Hash)]
pub enum BlockSymbol {
    Run(RunSymbolType, Exp),
    L,
    R,
    P,
    D,
}
fn add_or_merge_run(tape: &mut Vec<BlockSymbol>, run_type: RunSymbolType, nadd: Exp) {
    use BlockSymbol::*;
    match tape.last_mut() {
        Some(Run(t, n)) if *t == run_type => *n += nadd,
        _ => tape.push(Run(run_type, nadd)),
    }
}
fn decrement_run(tape: &mut Vec<BlockSymbol>, run_type: RunSymbolType) {
    use BlockSymbol::*;
    match tape.last_mut() {
        Some(Run(t, 1)) if *t == run_type => {
            tape.pop();
        }
        Some(Run(t, n @ 2..)) if *t == run_type => *n -= 1,
        _ => unreachable!("expected at least one of run symbol"),
    }
}
fn decrease_run_by(tape: &mut Vec<BlockSymbol>, run_type: RunSymbolType, nsub: Exp) {
    use BlockSymbol::*;
    match tape.last_mut() {
        Some(Run(t, n)) if *t == run_type && *n == nsub => {
            tape.pop();
        }
        Some(Run(t, n)) if *t == run_type && *n > nsub => *n -= nsub,
        _ => unreachable!("expected at least {} of run symbol", nsub),
    }
}
impl BlockSimulator {
    fn basic_step(&mut self) -> Result<Exp, SimError> {
        use HigherState::*;
        use BlockSymbol::*;
        use RunSymbolType::*;
        let n_steps = match (
            &self.state,
            self.left_tape.as_slice(),
            self.right_tape.as_slice(),
        ) {
            // L < -> L >
            (Left, [.., L], _) => {
                self.state = Right;
                1u128
            }
            // X < -> < X
            (Left, [.., Run(X, exp)], _) => {
                let n = *exp;
                self.left_tape.pop();
                add_or_merge_run(&mut self.right_tape, X, n);
                2u128 * n
            }
            // Q < D -> < C Q
            (Left, [.., Run(Q, _)], [.., D]) => {
                decrement_run(&mut self.left_tape, Q);
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, Q, 1u128);
                self.right_tape.push(Run(C, 1u128));
                1u128
            }
            // Q < C -> < F Q
            (Left, [.., Run(Q, _)], [.., Run(C, _)]) => {
                decrement_run(&mut self.left_tape, Q);
                decrement_run(&mut self.right_tape, C);
                add_or_merge_run(&mut self.right_tape, Q, 1u128);
                self.right_tape.push(Run(F, 1u128));
                1u128
            }
            // Q < X -> < C P
            (Left, [.., Run(Q, _)], [.., Run(X, _)]) => {
                decrement_run(&mut self.left_tape, Q);
                decrement_run(&mut self.right_tape, X);
                self.right_tape.push(P);
                self.right_tape.push(Run(C, 1u128));
                1u128
            }
            // Q < F P -> < F F
            (Left, [.., Run(Q, _)], [.., P, Run(F, 1)]) => {
                decrement_run(&mut self.left_tape, Q);
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, F, 2u128);
                1u128
            }
            // Q < F -> < F P
            (Left, [.., Run(Q, _)], [.., Run(F, _)]) => {
                decrement_run(&mut self.left_tape, Q);
                decrement_run(&mut self.right_tape, F);
                self.right_tape.push(P);
                self.right_tape.push(Run(F, 1u128));
                1u128
            }
            // Q < P -> < F
            (Left, [.., Run(Q, _)], [.., P]) => {
                decrement_run(&mut self.left_tape, Q);
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, F, 1u128);
                1u128
            }
            // Q < -> < P
            (Left, [.., Run(Q, _)], _) => {
                decrement_run(&mut self.left_tape, Q);
                self.right_tape.push(P);
                1u128
            }
            // > X -> X >
            (Right, _, [.., Run(X, exp)]) => {
                let n = *exp;
                self.right_tape.pop();
                add_or_merge_run(&mut self.left_tape, X, n);
                4u128 * n
            }
            // > D -> X s>
            (Right, _, [.., D]) => {
                self.state = RightSlow;
                self.right_tape.pop();
                add_or_merge_run(&mut self.left_tape, X, 1u128);
                4u128
            }
            // > C P -> < D F
            (Right, _, [.., P, Run(C, 1)]) => {
                self.state = Left;
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, F, 1u128);
                self.right_tape.push(D);
                6u128
            }
            // > C Q -> < D C
            (Right, _, [.., Run(Q, _), Run(C, 1)]) => {
                self.state = Left;
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, Q);
                add_or_merge_run(&mut self.right_tape, C, 1u128);
                self.right_tape.push(D);
                6u128
            }
            // > C -> < D P
            (Right, _, [.., Run(C, _)]) => {
                self.state = Left;
                decrement_run(&mut self.right_tape, C);
                self.right_tape.push(P);
                self.right_tape.push(D);
                6u128
            }
            // > F P -> < D X
            (Right, _, [.., P, Run(F, 1)]) => {
                self.state = Left;
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, X, 1u128);
                self.right_tape.push(D);
                6u128
            }
            // > F Q -> < D D
            (Right, _, [.., Run(Q, _), Run(F, 1)]) => {
                self.state = Left;
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, Q);
                self.right_tape.push(D);
                self.right_tape.push(D);
                6u128
            }
            // > F -> < D Q
            (Right, _, [.., Run(F, _)]) => {
                self.state = Left;
                decrement_run(&mut self.right_tape, F);
                add_or_merge_run(&mut self.right_tape, Q, 1u128);
                self.right_tape.push(D);
                6u128
            }
            // > Q F R -> X < D F R
            (Right, _, [.., R, Run(F, 1), Run(Q, 1)]) => {
                self.state = Left;
                self.right_tape.pop();
                add_or_merge_run(&mut self.left_tape, X, 1u128);
                self.right_tape.push(D);
                12u128
            }
            // > P R -> < D F R
            (Right, _, [.., R, P]) => {
                self.state = Left;
                self.right_tape.pop();
                self.right_tape.push(Run(F, 1u128));
                self.right_tape.push(D);
                8u128
            }
            // > Q R -> < Q F R
            (Right, _, [.., R, Run(Q, 1)]) => {
                self.state = Left;
                self.right_tape.pop();
                self.right_tape.push(Run(F, 1u128));
                self.right_tape.push(Run(Q, 1u128));
                8u128
            }
            // s> R -> < P D F R
            (RightSlow, _, [.., R]) => {
                self.state = Left;
                self.right_tape.push(Run(F, 1u128));
                self.right_tape.push(D);
                self.right_tape.push(P);
                14u128
            }
            // > P X -> > C P
            (Right, _, [.., Run(X, _), P]) => {
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, X);
                self.right_tape.push(P);
                self.right_tape.push(Run(C, 1u128));
                0u128
            }
            // > P D -> < D C
            (Right, _, [.., D, P]) => {
                self.state = Left;
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, C, 1u128);
                self.right_tape.push(D);
                6u128
            }
            // > P C -> > F Q
            (Right, _, [.., Run(C, _), P]) => {
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, C);
                add_or_merge_run(&mut self.right_tape, Q, 1u128);
                self.right_tape.push(Run(F, 1u128));
                0u128
            }
            // > P F -> > F P
            (Right, _, [.., Run(F, _), P]) => {
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, F);
                self.right_tape.push(P);
                self.right_tape.push(Run(F, 1u128));
                0u128
            }
            // > P P -> > F
            (Right, _, [.., P, P]) => {
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, F, 1u128);
                0u128
            }
            // > P Q -> > C
            (Right, _, [.., Run(Q, _), P]) => {
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, Q);
                add_or_merge_run(&mut self.right_tape, C, 1u128);
                0u128
            }
            // > Q X -> > D P
            (Right, _, [.., Run(X, _), Run(Q, 1)]) => {
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, X);
                self.right_tape.push(P);
                self.right_tape.push(D);
                0u128
            }
            // > Q D -> > D Q
            (Right, _, [.., D, Run(Q, 1)]) => {
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, Q, 1u128);
                self.right_tape.push(D);
                0u128
            }
            // > Q C -> X > Q
            (Right, _, [.., Run(C, exp), Run(Q, 1)]) => {
                let n = *exp;
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, Q, 1);
                add_or_merge_run(&mut self.left_tape, X, n);
                4u128 * n
            }
            // > Q F -> > X P
            (Right, _, [.., Run(F, _), Run(Q, 1)]) => {
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, F);
                self.right_tape.push(P);
                self.right_tape.push(Run(X, 1u128));
                0u128
            }
            // > Q P -> > X
            (Right, _, [.., P, Run(Q, 1)]) => {
                self.right_tape.pop();
                self.right_tape.pop();
                add_or_merge_run(&mut self.right_tape, X, 1u128);
                0u128
            }
            // > Q Q -> > D (1/2)
            (Right, _, [.., Run(Q, 2u128..)]) => {
                decrease_run_by(&mut self.right_tape, Q, 2u128);
                self.right_tape.push(D);
                0u128
            }
            // > Q Q -> > D (2/2)
            (Right, _, [.., Run(Q, _), Run(Q, 1)]) => {
                self.right_tape.pop();
                decrement_run(&mut self.right_tape, Q);
                self.right_tape.push(D);
                0u128
            }
            // s> X -> Q > P
            (RightSlow, _, [.., Run(X, _)]) => {
                self.state = Right;
                decrement_run(&mut self.right_tape, X);
                add_or_merge_run(&mut self.left_tape, Q, 1u128);
                self.right_tape.push(P);
                3u128
            }
            // s> D -> Q > Q
            (RightSlow, _, [.., D]) => {
                self.state = Right;
                self.right_tape.pop();
                add_or_merge_run(&mut self.left_tape, Q, 1u128);
                add_or_merge_run(&mut self.right_tape, Q, 1u128);
                3u128
            }
            // s> C -> Q Q >
            (RightSlow, _, [.., Run(C, _)]) => {
                self.state = Right;
                decrement_run(&mut self.right_tape, C);
                add_or_merge_run(&mut self.left_tape, Q, 2u128);
                6u128
            }
            // s> F -> Q Q s>
            (RightSlow, _, [.., Run(F, _)]) => {
                decrement_run(&mut self.right_tape, F);
                add_or_merge_run(&mut self.left_tape, Q, 2u128);
                6u128
            }
            // s> P -> Q s>
            (RightSlow, _, [.., P]) => {
                self.right_tape.pop();
                add_or_merge_run(&mut self.left_tape, Q, 1u128);
                3u128
            }
            // s> Q -> Q >
            (RightSlow, _, [.., Run(Q, _)]) => {
                self.state = Right;
                decrement_run(&mut self.right_tape, Q);
                add_or_merge_run(&mut self.left_tape, Q, 1u128);
                3u128
            }
            _ => return Err(SimError::UndefinedTransition),
        };
        Ok(n_steps)
    }
}
impl fmt::Display for BlockSimulator {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        use colored::*;
        const LEFT_PRINT_THRESHOLD: usize = 100;
        let l_th = LEFT_PRINT_THRESHOLD / 2;
        self.self_steps.fmt(f)?;
        write!(f, " | {}: ", self.base_steps)?;
        if self.left_tape.len() <= LEFT_PRINT_THRESHOLD {
            for symb in &self.left_tape {
                write!(f, "{} ", symb)?;
            }
        } else {
            for symb in &self.left_tape[..l_th] {
                write!(f, "{} ", symb)?;
            }
            write!(f, " ...{} terms... ", self.left_tape.len() - LEFT_PRINT_THRESHOLD)?;
            for symb in &self.left_tape[self.left_tape.len() - l_th..] {
                write!(f, "{} ", symb)?;
            }
        }
        match self.state {
            HigherState::Left => write!(f, "{}", "<".red().bold())?,
            HigherState::Right => write!(f, "{}", ">".red().bold())?,
            HigherState::RightSlow => write!(f, "{}", "s>".red().bold())?,
        }
        const RIGHT_PRINT_THRESHOLD: usize = 200;
        let r_th = RIGHT_PRINT_THRESHOLD / 2;
        if self.right_tape.len() <= RIGHT_PRINT_THRESHOLD {
            for symb in self.right_tape.iter().rev() {
                write!(f, " {}", symb)?;
            }
        } else {
            for symb in self.right_tape[self.right_tape.len() - r_th..].iter().rev() {
                write!(f, " {}", symb)?;
            }
            write!(
                f, " ...{} terms... ", self.right_tape.len() - RIGHT_PRINT_THRESHOLD
            )?;
            for symb in self.right_tape[..r_th].iter().rev() {
                write!(f, " {}", symb)?;
            }
        }
        Ok(())
    }
}

// End of autogenerated code

// Start of customizable code
type Exp = u128;
pub struct BlockSimulator {
    pub left_tape: Vec<BlockSymbol>,
    pub right_tape: Vec<BlockSymbol>,
    pub state: HigherState,
    pub base_steps: u128,
    pub self_steps: u64,
}
impl fmt::Display for BlockSymbol {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        use BlockSymbol::*;
        let s0 = match *self {
            Run(t, _) => &format!("{:?}", t),
            _ => &format!("{:?}", self),
        };
        let s_exp = match *self {
            Run(_, n) => if n == 1 { "" } else { &format!("^{}", n) }
            _ => "",
        };
        write!(f, "{}{}", s0, s_exp)
    }
}

// End of customizable code

impl BlockSimulator {
    pub fn new() -> Self {
        use BlockSymbol::*;
        use RunSymbolType::*;
        Self {
            left_tape: vec![L],
            right_tape: vec![R, Run(F, 1), D],
            state: HigherState::Right,
            base_steps: 13,
            self_steps: 0
        }
    }

    pub fn new_with_tape(left_tape: Vec<BlockSymbol>, state: HigherState, right_tape: Vec<BlockSymbol>) -> Self {
        Self {
            left_tape, right_tape, state,
            base_steps: 0,
            self_steps: 0
        }
    }

    pub fn step(&mut self) -> Result<(), SimError> {
        let new_base_steps = self.basic_step()?;
        self.base_steps = self.base_steps.checked_add(new_base_steps.into()).unwrap();
        self.self_steps += 1;
        Ok(())
    }
}